import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthContext from "@/context/AuthContext";
import SWRConfigContext from "./../context/SWRConfigContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const OpenSans = Open_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={OpenSans.className}>
      <body className="w-full max-w-screen-xl mx-auto overflow-auto">
        <AuthContext>
          <header className="sticky top-0 z-10 flex items-center bg-white border-b ">
            <Navbar />
          </header>

          <main className="flex justify-center w-full min-h-full bg-neutral-50">
            <SWRConfigContext> {children}</SWRConfigContext>
          </main>
        </AuthContext>
        <div id="portal"></div>
      </body>
    </html>
  );
}
